# Generated by Django 3.0.7 on 2020-06-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectlist', '0002_addusersinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddArticles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.ImageField(upload_to='images/')),
                ('article_topic', models.CharField(max_length=30)),
                ('pub_date', models.DateTimeField()),
                ('article_image', models.ImageField(upload_to='images/')),
                ('article_link', models.CharField(max_length=250)),
                ('article_description', models.CharField(max_length=150)),
            ],
        ),
    ]
