# Generated by Django 3.0.7 on 2020-06-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectlist', '0003_addarticles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addarticles',
            name='article_description',
            field=models.CharField(max_length=450),
        ),
    ]
